### ISSUE TITLE
Bezier curves?

### ISSUE THREAD

**Issue by seinecle** [rsandor/gury#17]
Hi,

Is it possible to draw and animate bezier curves with this library?

Thx,

Clement

**Comment by rsandor** [comment]
Clement,

Of course. The library simply wraps around canvas and provides some "support" features that make it easier to use. Here's a link that will explain how to draw the curves using canvas:

https://developer.mozilla.org/en/Canvas_tutorial/Drawing_shapes#Bezier_and_quadratic_curves

Cheers,
Ryan

**Comment by seinecle** [comment]
thx!
