### ISSUE TITLE
Automatically delegating events to added objects?

### ISSUE THREAD

**Issue by hunter9000** [rsandor/gury#8]
I'm adding objects to my canvas, and they have their own update and draw functions, which get called automatically after play() is started. However, I also want them have their own functions for event handling, such as mouseenter, mousedown, etc.

So instead of 

$g().add('myGuy', new Guy());
$g().mousedown('myGuy', handleMouseDown());

The mousedown events will be delegated to the objects themselves, so adding myGuy to the canvas will let it start receiving events automatically, like this:

$g().add('myGuy', new Guy());
// now when the mouse enters the Guy object's space, it will call the Guy object's mouseEnter function, etc.

I don't see anyway to set this up currently, is it possible, or can it be made possible?

**Comment by rsandor** [comment]
Good idea, I'm in the middle of redesigning the event system and this shouldn't be much of a problem. Give me a couple days and I should have it pushed out :).

Thanks!
Ryan

**Comment by hunter9000** [comment]
Awesome, thanks!

**Comment by rsandor** [comment]
Hey man,

So I added in automatic event setup when you add objects, just give them the appropriate functions and it should work. Also check out https://github.com/rsandor/gury/blob/master/demos/autoevent.html for an example of it in action.

Thanks for the idea and happy coding!
Ryan
